  add-timer[m
  asteroid-models[m
  bugfix-explosion-plays-on-start[m
  bugfix-explosions[m
  bugfix-explosions-sound-clipping[m
  bugfix-shield-display-mobile[m
  bugfix-timer-resets-on-comet-impact[m
  camera-effects[m
  destroy-explosions[m
  difficulty-scaling[m
  health-shields-system[m
  improve-code-style[m
* [32mmain[m
  main-menu[m
  pause-game[m
  pause-menu[m
  player-health[m
  player-high-score[m
  refactor-hit-detection[m
  refactor-ui-manager[m
  settings-main-menu[m
  star-shader[m
  stars-object-pool[m
  timer-score-game-over[m
  ui-score[m
  ui-stars[m
